### ISSUE TITLE
config breaking webm converter

### ISSUE THREAD

**Issue by ghost** [Tsubajashi/mpv-settings#14] opened 2021-05-30 04:08 UTC
```
[protocol-network]
force-window=immediate
```
this option breaks the [webm converter](https://github.com/ekisu/mpv-webm) for some reason.
open a video file from some url, try the webm converter (vp8), errors out (nothing specific)

**Comment by Tsubajashi** [comment] 2021-05-30 04:13
will try to reproduce after i slept.
though, immediate is there to have the screen instantly pop up even when it buffers so you know your system isnt hanging.

**Comment by Tsubajashi** [comment] 2021-06-04 08:58
can you confirm that its fixed? just commented the specific function.

**Comment by horusra** [comment] 2021-06-04 11:19
seems fixed now

**Comment by ghost** [comment] 2021-06-04 11:36
I can't really figure that out as now using this: https://raw.githubusercontent.com/Tsubajashi/mpv-settings/master/mpv_windows.conf
makes youtube-dl play normally for a minute or so, but then the audio continues while the video frame stops changing
reverting to my own config, youtube-dl works fine
something weird is going on but I'm not sure what

**Comment by Tsubajashi** [comment] 2021-06-04 13:24
can you send me your config so I can compare where the issue might comes from? didn't experience it on my end on 3 different devices with all OS I support

**Comment by ghost** [comment] 2021-06-13 13:16
I didn't change much, but this is my working config now:
https://pastebin.com/EgVFhb5B

**Comment by Tsubajashi** [comment] 2021-06-13 15:38
Thanks! i will look into it.

**Comment by Tsubajashi** [comment] 2021-08-07 18:18
after careful investigation, i still wasnt able to reproduce it on my end (on windows, mac, and linux). could you verify that it works with a newer version of MPV? plus, do you have - in any case - vsync disabled in your graphics cards software  ,or if you are on linux, you disabled it on a compositor level?
Also, sorry that it took me so long to get back to you.

**Comment by ghost** [comment] 2021-08-11 23:52
Still the same problem with latest mpv verion. Webm converter only works when I comment out `#force-window=immediate` under `[protocol-network]`

vsync is on(win10, using nvidia gpu)
turning vsync off for mpv makes the video play at a way faster speed than the audio, so I'm keeping vsync on.

**Comment by Tsubajashi** [comment] 2021-08-23 03:26
interesting. yea vsync should always stay on.
ill put your idea of the fix in my next cleanup of the repo. currently pretty busy building my TVP so mpv-settings got a backseat at first.

**Comment by Tsubajashi** [comment] 2021-08-27 19:44
just made a few more updates - can you redownload and check if it works for you? :)
if so, you can close the issue then - have fun with the new UI!

**Comment by Tsubajashi** [comment] 2021-08-27 19:45
i also added the webm converter to the config so you dont need to fiddle around with anything anymore :)

**Comment by ghost** [comment] 2021-08-29 01:56
> 
> 
> i also added the webm converter to the config so you dont need to fiddle around with anything anymore :)

Thank you!

**Comment by Tsubajashi** [comment] 2021-09-10 14:09
Since there was no response in 13 days, i think i can close the issue - i will reopen it if you still have the problem :)

**Closed as completed by Tsubajashi** 2021-09-10 14:09 UTC
