### ISSUE TITLE
Newer config file doesnt work for me

### ISSUE THREAD

**Issue by Dkfc123** [Tsubajashi/mpv-settings#31] opened 2022-12-22 05:32 UTC
The older mpv.conf works fine but the newer one just doesnt work for me, the application refuses to open
Here is my log file
[mpv.log](https://github.com/Tsubajashi/mpv-settings/files/10284005/mpv.log)

**Comment by Tsubajashi** [comment] 2022-12-22 08:11
Hi! does that happen to every video file in question, or does that only happen in particular situation?

**Comment by Tsubajashi** [comment] 2022-12-22 08:20
i now checked throughout the entire log, and im unsure where the issue is - as far as i have seen, it didnt even get any information to run any kind of video. Can you tell me your hardware you tried to run this on?

**Comment by Dkfc123** [comment] 2022-12-22 09:39
> Hi! does that happen to every video file in question, or does that only happen in particular situation?

It happens to every video file and even just opening the application itself without specifying any file it doesnt open

**Comment by Dkfc123** [comment] 2022-12-22 09:42
> 

Yes my GPU is Nvidia GeForce GTX 1050 with 3gb of VRAM as its the mobile version
My cpu is the Ryzen 5 3550h (4c/8t) 
I have made sure mpv uses the dedicated GPU using the windows graphics settings so i dont think the integrated GPU is part of the issue 
I also have 14GB of RAM and it is running off the boot drive which is an nvme SSD

**Comment by Dkfc123** [comment] 2022-12-22 09:58
Here is a log file of when i try to open a video in particular (The previous one was just double clicking the .exe)
[mpv.log](https://github.com/Tsubajashi/mpv-settings/files/10285781/mpv.log)

**Comment by Tsubajashi** [comment] 2022-12-22 11:22
there are 2 things you may want to check out, as i still dont get any critical errors listed in the logs:
- try to install the fonts delivered with the config
- grab yourself the v3 version of mpv from shinchiro https://sourceforge.net/projects/mpv-player-windows/files/64bit-v3/

after Christmas i will see if i can replicate the issue on Windows, as i generally dont run Windows anymore and would need to setup a test environment for that

**Comment by Tsubajashi** [comment] 2022-12-22 11:32
i have added another config file for windows, which may work on your end - i wasnt able to test it, but i essentially reverted gpu-next to gpu, and (hopefully) disabled all features which are incompatible with the old vo backend.
Please tell me if it works - if it does, this can be considered a workaround until i have a windows setup to test with

**Comment by Dkfc123** [comment] 2022-12-22 12:03
I installed the fonts in the fonts folder and have been using v3 
However, neither the old nor the new safe .conf files have been working for me
Just want to mention the config used in an older version of your settings still works fine for me 
[mpv.log](https://github.com/Tsubajashi/mpv-settings/files/10286715/mpv.log)
This is that .conf file (Renamed so i can upload it)
[mpv.conf.log](https://github.com/Tsubajashi/mpv-settings/files/10286726/mpv.conf.log)

**Comment by Tsubajashi** [comment] 2022-12-22 12:18
thank you, i will add the old config as the safe_conf for the time being. :)

**Comment by Xathros1** [comment] 2022-12-22 12:45
there is no need to install any of the fonts inside the fonts folder, they are preloaded before being used by mpv automatically 
https://mpv.io/manual/stable/#files-~/-config/mpv/fonts/

**Comment by Xathros1** [comment] 2022-12-22 13:22
I've tried the latest stable version which is mpv 2022.11.14 on a windows test system and it worked for me without any errors. So I can't replicate...
Maybe @TrumpetMonkey could try the stable version instead? It's possible that mpv devs have introduced some bugs in the new git releases. Who knows. I'm just guessing here. The logs weren't helpful at all unfortunately.
https://sourceforge.net/projects/mpv-player-windows/files/release/ 
[mpv-0.35.0-x86_64.7z](https://sourceforge.net/projects/mpv-player-windows/files/release/mpv-0.35.0-x86_64.7z/download)
or
[mpv-0.35.0-x86_64-v3.7z](https://sourceforge.net/projects/mpv-player-windows/files/release/mpv-0.35.0-x86_64-v3.7z/download)

Also what could help us is that you try to start mpv and / or a testvideo via powershell/commandline and report any errors that you encounter. Maybe it'll show stuff, that the logs don't?

**Comment by Xathros1** [comment] 2022-12-22 13:54
> i have added another config file for windows, which may work on your end - i wasnt able to test it, but i essentially reverted gpu-next to gpu, and (hopefully) disabled all features which are incompatible with the old vo backend. Please tell me if it works - if it does, this can be considered a workaround until i have a windows setup to test with

Just use the repo from before the changes to gpu-next 
https://github.com/Tsubajashi/mpv-settings/tree/0d9218ecc8c92c60f95261820f3f71232cb6ec9c

**Comment by Xathros1** [comment] 2022-12-22 15:27
> I have made sure mpv uses the dedicated GPU using the windows graphics settings so i dont think the integrated GPU is part of the issue

start mpv with 
--vulkan-device=help
https://mpv.io/manual/stable/#options-vulkan-device
By default mpv is using the first entry.

To do that you need to open commandline/powershell, switch to the mpv directory using "cd" for e.g.:
cd C:\ProgramData\mpv.install\
and then run 
mpv.com --vulkan-device=help

**Comment by Dkfc123** [comment] 2022-12-22 17:10
> I've tried the latest stable version which is mpv 2022.11.14 on a windows test system and it worked for me without any errors. So I can't replicate... Maybe @TrumpetMonkey could try the stable version instead? It's possible that mpv devs have introduced some bugs in the new git releases. Who knows. I'm just guessing here. The logs weren't helpful at all unfortunately. https://sourceforge.net/projects/mpv-player-windows/files/release/ [mpv-0.35.0-x86_64.7z](https://sourceforge.net/projects/mpv-player-windows/files/release/mpv-0.35.0-x86_64.7z/download) or [mpv-0.35.0-x86_64-v3.7z](https://sourceforge.net/projects/mpv-player-windows/files/release/mpv-0.35.0-x86_64-v3.7z/download)
> 
> Also what could help us is that you try to start mpv and / or a testvideo via powershell/commandline and report any errors that you encounter. Maybe it'll show stuff, that the logs don't?

Hi i have now tried the version that you have linked and unfortunately the results are still much the same
I also used the --vulkan-device=help and my dedicated gpu is first in the list as GPU0 so i think it is safe to assume it is using that
Here is a transcript of what appeared in powershell once i tried to load up a test video (With the newest version)

[powershell.txt](https://github.com/Tsubajashi/mpv-settings/files/10289048/powershell.txt)

**Comment by Xathros1** [comment] 2022-12-22 23:11
Thanks!
I can't find anything wrong. My best guess is compatibility issues with drivers to the new libplacebo renderer (gpu-next) although there are no error messages, no, warnings, nothing.

**Comment by Xathros1** [comment] 2022-12-22 23:48
Could you try my alternative conf here? 
https://github.com/Xathros1/mpv-settings-gpu-next/blob/compat-gpu/mpv_windows_safe.conf
This is just a very slightly changed version for vo=gpu (some settings don't translate 1 to 1)
if this works then we have found the culprit

**Comment by Dkfc123** [comment] 2022-12-23 15:29
> Could you try my alternative conf here? https://github.com/Xathros1/mpv-settings-gpu-next/blob/compat-gpu/mpv_windows_safe.conf This is just a very slightly changed version for vo=gpu (some settings don't translate 1 to 1) if this works then we have found the culprit

This one doesnt seem to work either
I would like to mention that indeed i am on the latest nvidia game drivers for windows and
 on windows11

Here is the powershell windows transcript and log file while trying to play a video with the newest config 
[powershellnew.txt](https://github.com/Tsubajashi/mpv-settings/files/10295928/powershellnew.txt)
And the log
[newconf.log](https://github.com/Tsubajashi/mpv-settings/files/10295932/newconf.log)

**Comment by Xathros1** [comment] 2022-12-23 16:13
> This one doesnt seem to work either
> I would like to mention that indeed i am on the latest nvidia game drivers for windows and
> on windows11

Thanks, for trying! I haven't expected you to use 5 year old drivers anyway, also I think mpv would be complaining then, definitely.
Still nothing in the logs.

OK, here is another test config... 
this time using the new renderer (gpu-next) and DirectX instead of Vulkan.
https://github.com/Xathros1/mpv-settings-gpu-next/blob/compat-gpu/mpv_windows_d3d.conf

**Comment by Dkfc123** [comment] 2022-12-23 18:33
> > This one doesnt seem to work either
> > I would like to mention that indeed i am on the latest nvidia game drivers for windows and
> > on windows11
> 
> Thanks, for trying! I haven't expected you to use 5 year old drivers anyway, also I think mpv would be complaining then, definitely. Still nothing in the logs.
> 
> OK, here is another test config... this time using the new renderer (gpu-next) and DirectX instead of Vulkan. https://github.com/Xathros1/mpv-settings-gpu-next/blob/compat-gpu/mpv_windows_d3d.conf

Finally! this one works completely normally for me, although im not sure why it wouldnt work with the vulkan version

**Comment by Xathros1** [comment] 2022-12-23 19:42
> Finally! this one works completely normally for me, although im not sure why it wouldnt work with the vulkan version

Great, so we've found the culprit.... the gpu api. 

Why? Don't know.

Although: "because GPU drivers on Windows are a mess and you can trust them to do DX11, but not much beyond that. Especially Intel." 
https://github.com/mpv-player/mpv/issues/8902#issuecomment-856955992

maybe a valid reason...

It's entirely possible that this issue will be gone with some future driver update from Nvidia

**Comment by Dkfc123** [comment] 2022-12-24 07:03
> > Finally! this one works completely normally for me, although im not sure why it wouldnt work with the vulkan version
> 
> Great, so we've found the culprit.... the gpu api.
> 
> Why? Don't know.
> 
> Although: "because GPU drivers on Windows are a mess and you can trust them to do DX11, but not much beyond that. Especially Intel." [mpv-player/mpv#8902 (comment)](https://github.com/mpv-player/mpv/issues/8902#issuecomment-856955992)
> 
> maybe a valid reason...
> 
> It's entirely possible that this issue will be gone with some future driver update from Nvidia

Until then i will be using the d3d config 
Thanks for the help!

**Comment by HealthyMindFrsh** [comment] 2022-12-30 20:09
You guys should probably try checking this video out, I believe all of your answers are here:
https://youtu.be/NnA8pJvbeHg

Also I can't wait for TVP Beta 8! Keep up the good work Tsuba! I'll be maining TVPOS when it comes out :)

**Comment by Tsubajashi** [comment] 2023-11-09 16:01
> > > Finally! this one works completely normally for me, although im not sure why it wouldnt work with the vulkan version
> > 
> > 
> > Great, so we've found the culprit.... the gpu api.
> > Why? Don't know.
> > Although: "because GPU drivers on Windows are a mess and you can trust them to do DX11, but not much beyond that. Especially Intel." [mpv-player/mpv#8902 (comment)](https://github.com/mpv-player/mpv/issues/8902#issuecomment-856955992)
> > maybe a valid reason...
> > It's entirely possible that this issue will be gone with some future driver update from Nvidia
> 
> Until then i will be using the d3d config Thanks for the help!

just wanted to check on ya again - are the issues resolved with the current mpv master + gpu drivers you have, nowadays?
if so, i would like to close this issue :D

**Comment by Dkfc123** [comment] 2023-11-09 22:16
i dont use this config anymore but i do use MPV with vulkan now so

**Comment by Tsubajashi** [comment] 2023-11-10 11:20
gotcha, then ill close it for the moment. :) thanks for letting me know!

**Closed as completed by Tsubajashi** 2023-11-10 11:20 UTC
