### ISSUE TITLE
Font issue

### ISSUE THREAD

**Issue by notDavid** [Tsubajashi/mpv-settings#19] opened 2022-09-17 18:56 UTC
Hi there, any idea how to fix this issue? I've installed the Font but... it doesn't seem to work.

Thank you :-)

macOS 12.6 (M1)

<img width="1496" alt="2022-09-17_20-49-37" src="https://user-images.githubusercontent.com/1530401/190872341-e922a650-5abd-48d9-b3b4-49d64bd9040d.png">

**Comment by Tsubajashi** [comment] 2022-09-17 19:38
as soon as i have my hands on a mac, i will check if theres something wrong with it. 
https://github.com/Tsubajashi/mpv-settings/issues/16
we had that issue once, and one other user confirmed if that idea worked or not.
im not sure when i have access to a mac, but ill make sure to have it asap.

**Comment by notDavid** [comment] 2022-09-18 06:37
Great, thank you for looking into it.

**Comment by Tsubajashi** [comment] 2022-11-18 09:16
Status Report: i still wasnt able to replicate the bug even after speaking with 8 friends who run macs daily. as soon as i have a mac for testing myself, i try to replicate it asap :) sorry for the long wait!

**Comment by notDavid** [comment] 2022-11-18 18:47
Thank you @Tsubajashi , if you want me to test anything let me know.

> after speaking with 8 friends who run macs daily

I assume some of them also use M1 Mac's ?

**Comment by Tsubajashi** [comment] 2022-11-18 18:49
all of them run m1 macs, and some also used developer versions of ventura by that time i saw them

**Comment by Xathros1** [comment] 2022-11-22 00:56
> Status Report: i still wasnt able to replicate the bug even after speaking with 8 friends who run macs daily. as soon as i have a mac for testing myself, i try to replicate it asap :) sorry for the long wait!

got the same error with the new mpv release on linux. It's not font related. osc script is just broken.

**Comment by Tsubajashi** [comment] 2022-11-22 06:49
![image](https://user-images.githubusercontent.com/21346945/203244315-a62ec970-2a83-4dd1-a924-f57b82cc2d1a.png)
again, i cant reproduce it at all.
just freshly installed mpv from the arch repos just to make sure it wasnt flatpak related that it just worked - and no matter which version i pick, even running it on windows, i cant reproduce it.

**Comment by Tsubajashi** [comment] 2022-11-23 10:15
@notDavid can you check if the recent merges fixed it for you?

**Comment by notDavid** [comment] 2022-11-23 10:27
Thank you @Tsubajashi , I'm afraid it was not fixed yet...:

![mpv](https://user-images.githubusercontent.com/1530401/203523979-03de48ee-3a63-4bf0-b7b0-70e0975554a2.png)

**Comment by Xathros1** [comment] 2022-11-23 10:38
As a workaround until we figure it out you can delete the mordenx.lua in scripts and set osc=yes in mpv.conf

**Comment by Tsubajashi** [comment] 2022-12-04 22:04
@notDavid as of right now, mordenx has been removed. It will come back at a later date if those issues can be fixed :)

**Comment by Tsubajashi** [comment] 2022-12-08 14:16
@notDavid can you verify that this bug does not happen for you anymore?

**Comment by notDavid** [comment] 2022-12-08 16:04
@Tsubajashi Yes, thank you for the workaround!

<details>
  <summary>screenshot:</summary>
	
<img width="960" alt="Screenshot 2022-12-08 at 17 02 42" src="https://user-images.githubusercontent.com/1530401/206497862-90469432-c842-4dfb-95e9-45500ce88727.png">

</details>

**Comment by Tsubajashi** [comment] 2022-12-08 16:06
> @Tsubajashi Yes, thank you for the workaround!
> 
> <details>
>   <summary>screenshot:</summary>
> 	
> <img width="960" alt="Screenshot 2022-12-08 at 17 02 42" src="https://user-images.githubusercontent.com/1530401/206497862-90469432-c842-4dfb-95e9-45500ce88727.png">
> 
> </details>
> 
> 

no need to thank me, @Xathros1 seems to have found the workaround by speaking with upstream. credits fully to them :D

**Comment by Xathros1** [comment] 2022-12-08 18:41
All credits to the authors and the guy who made the pull request. I've just updated the file here. 

But I think we can close this then

**Comment by Tsubajashi** [comment] 2022-12-08 18:46
for sure!

**Closed as completed by Tsubajashi** 2022-12-08 18:46 UTC
